### ISSUE TITLE
Package installation

### ISSUE THREAD

**Issue by Ahmedali952** [MaisJamal/NN-based-grasping#1]
Can I get guidance regarding the installation of this package? 
What commands are required to be executed to install this package?

**Comment by MaisJamal** [comment]
Step 1
Install all of these:

sudo apt-get install ros-kinetic-control-toolbox ros-kinetic-controller-interface ros-kinetic-controller-manager ros-kinetic-joint-limits-interface ros-kinetic-transmission-interface ros-kinetic-moveit-core ros-kinetic-moveit-planners ros-kinetic-moveit-ros-planning

Step 2
clone industrial core to src in your workspace:
   git clone https://github.com/OrebroUniversity/industrial_core.git
and then build it:
    catkin_make


I should mention that I still have one problem with the package, that the object slips from the gripper while grasping. Probably it is an issue related to the gripper controllers.

**Comment by Ahmedali952** [comment]
@MaisJamal, thanks for your reply.
Built the package successfully.
Thanks.

**Comment by Ahmedali952** [comment]
@MaisJamal, can you also please guide regarding the neural network training and object detection through YuMi?
